stages:
  - buildTest
  - runTest
  - buildApp
  - deployGCP

variables:
  APP_IMAGE: $CI_REGISTRY_IMAGE/app
  TEST_IMAGE: $CI_REGISTRY_IMAGE/test

buildTest:
  stage: buildTest
  script:
    - docker build -f Dockerfile.test -t IMAGE .
    - docker push $TEST_IMAGE

runTest:
  stage: runTest
  script:
    - docker pull IMAGE
    - docker run IMAGE

buildApp:
  stage: buildApp
  script:
    - docker build -t IMAGE .
    - docker push IMAGE

deployGCP:
  stage: deployGCP
  script:
  "docker pull $APP_IMAGE && docker stop app || true && docker rm app || true && docker run -d --name app -p 80:5000 $APP_IMAGE"
