stages:
  - buildTest
  - runTest
  - buildApp
  - deployGCP

variables:
  APP_IMAGE: $CI_REGISTRY_IMAGE/app
  TEST_IMAGE: $CI_REGISTRY_IMAGE/test

buildTest:
  stage: buildTest
  script:
    - docker build -f Dockerfile.test -t $TEST_IMAGE .
    - docker push $TEST_IMAGE

runTest:
  stage: runTest
  script:
    - docker pull $TEST_IMAGE
    - docker run $TEST_IMAGE

buildApp:
  stage: buildApp
  script:
    - docker build -t $APP_IMAGE .
    - docker push $APP_IMAGE

deployGCP:
  stage: deployGCP
  script:
    - ssh -i $GCP_SSH_KEY $GCP_USER@$GCP_VM "docker pull $APP_IMAGE && docker stop app || true && docker rm app || true && docker run -d --name app -p 80:5000 $APP_IMAGE"
